services:
  - type: web
    name: image-scraper
    runtime: node
    buildCommand: npm install && npx playwright install chromium
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/.cache/ms-playwright 